### ISSUE TITLE
Caption formatting doesn't show properly or appears as NaN:NaN.

### ISSUE THREAD

**Issue by consandstuff** [TarheelGrad1998/gallery-card#11]
I'm using this format for my video captions: %d/%m %H:%M but in the card it only has 1 digit for day, month, hours and minutes (instead of two), so if the file has this name 2021_04_15_09_57 the caption shows as: 5/4 9:7 [00:16], instead of 15/04 09:57.

This is my yalm config:

```
type: 'custom:gallery-card'
entities:
  - camera.front_cam
  - path: 'media-source://media_source/local/folder-name'
    recursive: false
maximum_files: '10'
file_name_format: '%YYY_%m_%d_%H_%M'
caption_format: '%d/%m %H:%M '
menu_alignment: Responsive
```

![image](https://user-images.githubusercontent.com/32574103/115036129-3ae2e580-9e9b-11eb-9d2a-0a52df1b40b5.png)

Also, if the filename has the hour as 1 digit (9_57 instead of 09_57) the card shows the caption as NaN:NaN.

The rest of the card works great though! really happy with your work.
