### ISSUE TITLE
Error in LIne 259

### ISSUE THREAD

**Issue by gartenbauer** [TarheelGrad1998/gallery-card#13]
Hi, I get the fallowing error:
> Logger: frontend.js.latest.202104073
> Source: components/system_log/__init__.py:190
> First occurred: 5:00:07 (3 occurrences)
> Last logged: 7:00:06
> http://XXXX:8123/hacsfiles/gallery-card/gallery-card.js:259:51 Uncaught SyntaxError: Unexpected token ?

Which is:
https://github.com/TarheelGrad1998/gallery-card/blob/c3ca7591f950d8bc669842bbfa67c2cb6642fd61/gallery-card.js#L259

My config looks like this:
```
type: 'custom:gallery-card'
menu_alignment: Hidden
entities:
  - path: 'media-source://media_source/local/slideshow' 
    recursive: false
slideshow_timer: '5'
```
