### ISSUE TITLE
Trouble showing media source

### ISSUE THREAD

**Issue by AnthonyKNorman** [TarheelGrad1998/gallery-card#37]
Hi

error in card:
```
Path does not exist. media-source://media_source/local/front_drive/plant.jpg
```

yaml:
```
type: custom:gallery-card
entities:
  - path: media-source://media_source/local/front_drive/plant.jpg
```

Run this in a browser and it produces the required image
```
http://192.168.68.130:8123/local/front_drive/plant.jpg
````

Is there anything else I can tell you?

Thanks

**Comment by AnthonyKNorman** [comment]
Hi, sorry

I now realise I was using the wrong directory.
Card works great, Thank you.

**Comment by TarheelGrad1998** [comment]
Glad you like it.  Thanks!

**Comment by dbolton** [comment]
I could benefit from more complete examples. For example, how do I reference the images in /config/nest/event_media/6a9f9a6fbd8692dc5ef63004c98a09fb using media-source (ideally) or any other method? 

![image](https://github.com/TarheelGrad1998/gallery-card/assets/712270/16f3b41e-d719-4d05-907b-1b953001599a)

card yaml (camera.front_door works, but none of the attempt to reference the snapshot images from the camera work. 
```
type: custom:gallery-card
entities:
  - camera.front_door
  - sensor.nest
  - path: media-source://media_source/6a9f9a6fbd8692dc5ef63004c98a09fb/
  - path: >-
      media-source://media_source/local/config/nest/event_media/6a9f9a6fbd8692dc5ef63004c98a09fb/
  - path: media-source://api/nest/event_media/6a9f9a6fbd8692dc5ef63004c98a09fb/
menu_alignment: Responsive
maximum_files: 10
file_name_format: YYYYMMDD-HHmmss
caption_format: M/D h:mm A
```

config/configuration.yaml
```
sensor: 
  - platform: folder
    folder: /config/nest
```

I can see the images in the companion app under Media side bar > Nest > Front Door: Recent Events
