### ISSUE TITLE
Does not find any videos in local media

### ISSUE THREAD

**Issue by bsafh** [TarheelGrad1998/gallery-card#46]
Error message:

![image](https://user-images.githubusercontent.com/106388187/199062676-451d55c9-a1d4-4b84-878c-4f6411bdc18d.png)
`Invalid path. media-source://media_source/video/Japan`

the media browser in HA does find the videos, URL is:

[http://192.168.80.21:8123/media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Fvideo%2F./%2Cmedia-source%3A%2F%2Fmedia_source%2Fvideo%2FJapan](http://192.168.80.21:8123/media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Fvideo%2F./%2Cmedia-source%3A%2F%2Fmedia_source%2Fvideo%2FJapan
)

This translates to `media-source://media_source/,media-source://media_source/video/./,media-source://media_source/video/Japan `without UTL-Encoding, so the path `media-source://media_source/video/Japan/ `seems to be correct

It's HA Supervised installation (latest 2022.10.x) on Debioan, the "real" path is
`root@homeassistant:/usr/share/hassio/media/video/Japan`, the HassIO docker container sees this as `/media/video/Japan`

And yes, there are videos in there...

so, what's wrong here?

```
type: custom:gallery-card
entities:
  - path: media-source://media_source/video/Japan
    recursive: true
title: Japan Videos
show_reload: true
menu_alignment: responsive

```
