### ISSUE TITLE
Live camera covers menu thumbnails

### ISSUE THREAD

**Issue by styelz** [TarheelGrad1998/gallery-card#50]
Since the last update, all of the thumbnails in the menu which i have set  to "Bottom" are covered by the main camera feed. I've tried using Hidden and Top and get the same result. 

I am using he Latest chrome and gallery-card from HACS. All cameras are setup using the MotionEye add-on.

Here's what it looks like when the live camera feed is active.
![image](https://user-images.githubusercontent.com/17960160/204290377-9240b8ce-94a0-41d1-8ace-3cd211cf1780.png)

When i select one of the thumbnails, the menu thumbs display correctly.
![image](https://user-images.githubusercontent.com/17960160/204291980-bd24351b-41cd-458e-a627-ee888f81eac9.png)

**RAW CODE SAMPLE:**
```
type: horizontal-stack
cards:
  - type: custom:gallery-card
    menu_alignment: Bottom
    entities:
      - camera.front_door
      - path: media-source://media_source/local/Camera1/Videos
        recursive: false
    maximum_files_per_entity: false
    show_reload: true
    maximum_files: '5'
    view_layout:
      position: main
  - type: custom:gallery-card
    menu_alignment: Bottom
    entities:
      - camera.camera2
      - path: media-source://media_source/local/Camera2/Videos
        recursive: false
    maximum_files_per_entity: false
    show_reload: true
    maximum_files: '5'
    view_layout:
      position: main
  - type: custom:gallery-card
    menu_alignment: Bottom
    entities:
      - camera.camera3
      - path: media-source://media_source/local/Camera3/Videos
        recursive: false
    maximum_files_per_entity: false
    show_reload: true
    maximum_files: '5'
    view_layout:
      position: main
```
