### ISSUE TITLE
Path does not exist

### ISSUE THREAD

**Issue by dnestico** [TarheelGrad1998/gallery-card#52]
Honestly lost with this card just nothing works and when it does it's super slow.... 

It keeps complaining directory does not exist but under the media it literally does!

All I am trying to do is get the Frigate video Clips to show in the card, that's it!

<img width="824" alt="Screen Shot 2023-01-20 at 3 43 16 PM" src="https://user-images.githubusercontent.com/3034555/213801716-61a03293-b39f-4998-af2e-fbd47029d29e.png">

```
type: custom:gallery-card
menu_alignment: Bottom
entities:
  - path: media-source://media_source/local/Frigate/Clips/
    recursive: true
show_reload: true
```
